{
	"version": 1536261190,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/ringblue1-sheet0.png",
		"images/ringwhite2-sheet0.png",
		"images/ringblue3-sheet0.png",
		"images/ringwhite1-sheet0.png",
		"images/theball-sheet0.png",
		"images/ringblue4-sheet0.png",
		"images/particles.png",
		"images/ringwinner-sheet0.png",
		"images/backgroundbackup.png",
		"images/ringwhite3-sheet0.png",
		"images/ringblue2-sheet0.png",
		"images/bitchblue-sheet0.png",
		"images/bitchwhite-sheet0.png",
		"images/bitchgreen-sheet0.png",
		"images/bitchdamage-sheet0.png",
		"images/bitchtimefreezer-sheet0.png",
		"images/pauselogo-sheet0.png",
		"images/touchup-sheet0.png",
		"images/touchdown-sheet0.png",
		"images/touchleft-sheet0.png",
		"images/touchright-sheet0.png",
		"images/resumebutton-sheet0.png",
		"images/restartlevel-sheet0.png",
		"images/retartbutton-sheet0.png",
		"images/nextlevel-sheet0.png",
		"images/lifebonusdisplayer-sheet0.png",
		"images/lifereduceddisplayer-sheet0.png",
		"images/blueghosting-sheet0.png",
		"images/timefreezedisplay-sheet0.png",
		"images/whiteghostingdispaly-sheet0.png",
		"images/gamename-sheet0.png",
		"images/startbutton-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/level loss.m4a",
		"media/level loss.ogg",
		"media/life bonus.m4a",
		"media/life bonus.ogg",
		"media/life loss sound .m4a",
		"media/life loss sound .ogg",
		"media/spark.m4a",
		"media/spark.ogg",
		"media/fast-freezing-ice.m4a",
		"media/fast-freezing-ice.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"gloriahallelujah-webfont.eot",
		"gloriahallelujah-webfont.svg",
		"gloriahallelujah-webfont.ttf",
		"gloriahallelujah-webfont.woff",
		"gloriahallelujah-webfont.woff2",
		"stylesheet.css"
	]
}